<Project>
	<PropertyGroup>
		<!-- Build -->
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

		<!-- Version -->
		<Version>0.1.0-alpha.1</Version>

		<!-- Repository / SourceLink -->
		<RepositoryUrl>https://github.com/iuliansilitra/relay-hook</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/iuliansilitra/relay-hook</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<DebugType>portable</DebugType>

		<!-- NuGet metadata -->
		<Authors>iuliansilitra</Authors>
		<Copyright>Copyright © 2026 iuliansilitra</Copyright>
		<PackageTags>webhook;webhooks;callback;callbacks;reliable;delivery;outbound;sqlserver;aspnetcore;retry</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReleaseNotes>See https://github.com/iuliansilitra/relay-hook/releases</PackageReleaseNotes>

		<!-- NuGet output -->
		<PackageOutputPath>$(MSBuildThisFileDirectory)artifacts/packages</PackageOutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsPackable)' != 'false'">
		<None Include="$(MSBuildThisFileDirectory)README.md"
			  Pack="true"
			  PackagePath="\" />

		<None Include="$(MSBuildThisFileDirectory)logo.png"
			  Pack="true"
			  PackagePath="\" />
	</ItemGroup>
</Project>